config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:company, :job_title, :location, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/_hearder.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Job App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to 'Jobs', jobs_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'New Job', new_job_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :job_title, style: "display: block" %>
    <%= form.text_field :job_title %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">

  <div class="card" style="width: 18rem; margin: 40px">
  <div class="card-body">
    <p class="card-text">
    <strong>Company:</strong>
    <%= job.company %>
  </p>

  <p class="card-text">
    <strong>Job title:</strong>
    <%= job.job_title %>
  </p>

  <p class="card-text">
    <strong>Location:</strong>
    <%= job.location %>
  </p>

  <p class="card-text">
    <strong>Description:</strong>
    <%= job.description %>
  </p>
  </div>
</div>

</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>



<div class="btn-group" role="group" aria-label="Basic outlined example">
  <button type="button" class="btn btn-outline-primary" style="text-decoration: none; color: black"><%= link_to "Show this job", @job %></button>
  <button type="button" class="btn btn-outline-primary"><%= link_to "Back to jobs", jobs_path %></button>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="text-align: center">Jobs List</h1>

<div id="jobs" style="margin: 40px">
<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Company</th>
        <th>Job Title</th>
        <th>Location</th>
        <th>Description</th>
        <th> </th>
      </tr>
    </thead>

  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= job.company %></td>  
      <td><%= job.job_title %></td>
      <td><%= job.location %></td>
      <td><%= job.description %></td>
      <td><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %><%= link_to "Show this job", job, class: "btn btn-outline-secondary btn-sm" %></td>     
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New job", new_job_path, class:"btn btn-secondary" %>
</div>

app/views/jobs/new.html.erb
<div class="card text-bg-light mb-3 text-center" style="max-width: 18rem; display: inline">
  <div class="card-header">New Job</div>
  <div class="card-body">
    <p class="card-text"><%= render "form", job: @job %></p>
    <%= link_to "Back to jobs", jobs_path %>
  </div>
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'home/hearder' %>
    <%= yield %><br>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>